### ISSUE TITLE
W605 - switched anti-pattern with best practice 

### ISSUE THREAD

**Issue by hnykda** [LintlyCI/Flake8Rules#7]
Isn't the Best practice with Anti-pattern inverted in rule https://lintlyci.github.io/Flake8Rules/rules/W605.html

**Comment by yablonsky** [comment]
I agree that this is a mistake.
Even in [pycodestyle tests](https://github.com/PyCQA/pycodestyle/blob/eb91b79ab38aad4d44a3b52b02605412f32ba5ae/testsuite/W60.py#L23) and [source](https://github.com/PyCQA/pycodestyle/blob/f4f6e556faea76809b70413fea9f496288d56713/pycodestyle.py#L1503) it says that `r'\.png$'` is Okay

**Comment by hnykda** [comment]
Who should I notify. @grantmcconnaughey ?

**Comment by grantmcconnaughey** [comment]
Fixed! Thanks for bringing it up.
